# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_xbar_0/Accumulator_bd_xbar_0.xci
# IP: The module: 'Accumulator_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_xbar_0/Accumulator_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Accumulator_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_xbar_0/Accumulator_bd_xbar_0.xci
# IP: The module: 'Accumulator_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_xbar_0/Accumulator_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Accumulator_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
