# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/axis_data_fifo_0/axis_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# Block Designs: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/Accumulator_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd || ORIG_REF_NAME==Accumulator_bd} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_zynq_ultra_ps_e_0_0/Accumulator_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Accumulator_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_axi_dma_0_0/Accumulator_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_axi_dma_0_0 || ORIG_REF_NAME==Accumulator_bd_axi_dma_0_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_axi_gpio_0_0/Accumulator_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_axi_gpio_0_0 || ORIG_REF_NAME==Accumulator_bd_axi_gpio_0_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_axi_gpio_0_1/Accumulator_bd_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_axi_gpio_0_1 || ORIG_REF_NAME==Accumulator_bd_axi_gpio_0_1} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_rst_ps8_0_100M_0/Accumulator_bd_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_rst_ps8_0_100M_0 || ORIG_REF_NAME==Accumulator_bd_rst_ps8_0_100M_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_xbar_0/Accumulator_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_xbar_0 || ORIG_REF_NAME==Accumulator_bd_xbar_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_auto_ds_0/Accumulator_bd_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_auto_ds_0 || ORIG_REF_NAME==Accumulator_bd_auto_ds_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_auto_pc_0/Accumulator_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_auto_pc_0 || ORIG_REF_NAME==Accumulator_bd_auto_pc_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_ps8_0_axi_periph_0/Accumulator_bd_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_ps8_0_axi_periph_0 || ORIG_REF_NAME==Accumulator_bd_ps8_0_axi_periph_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_axi_smc_0/Accumulator_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_axi_smc_0 || ORIG_REF_NAME==Accumulator_bd_axi_smc_0} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/ip/Accumulator_bd_Accumulator_0_0/Accumulator_bd_Accumulator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Accumulator_bd_Accumulator_0_0 || ORIG_REF_NAME==Accumulator_bd_Accumulator_0_0} -quiet] -quiet

# IP: ip/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# XDC: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-SimpleDMA/src/bd/Accumulator_bd/Accumulator_bd_ooc.xdc
